<a href="https://colab.research.google.com/github/PrajaktaPatil1/benign_malignant/blob/master/benign_malignant(with_GLCM_feature).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [53]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import os
from glob import glob
from PIL import Image

In [54]:
import os
import numpy as np
from skimage.feature import local_binary_pattern
from skimage.color import rgb2gray
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [55]:
import cv2
from skimage.feature import greycomatrix, greycoprops

In [56]:
from google.colab import files
uploaded = files.upload()

Saving archive (update1).zip to archive (update1).zip


In [69]:
import os
import zipfile

# Path to the zip file
zip_file_path = '/content/archive (update1).zip'

# Directory where you want to extract the files
extracted_dir = '/content/extracted_data'

# Ensure the directory exists
os.makedirs(extracted_dir, exist_ok=True)

# Extract the contents of the zip file
with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall(extracted_dir)

# List the contents of the extracted directory
extracted_files = os.listdir(extracted_dir)
print("Contents of the extracted directory:")
for file_name in extracted_files:
    print(file_name)

# Destination directory to save the extracted files
save_dir = '/content/saved_files'

Contents of the extracted directory:
archive (4)


In [70]:
# Step 1: Data Preprocessing

def extract_glcm_features(image):
    # Convert image to grayscale if it's not already
    if len(image.shape) > 2:
        gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    else:
        gray = image
    # Calculate GLCM
    distances = [1]  # distance between pixels
    angles = [0, np.pi/4, np.pi/2, 3*np.pi/4]  # angles for co-occurrence matrix
    glcm = greycomatrix(gray, distances=distances, angles=angles, symmetric=True, normed=True)
    # Calculate GLCM properties
    contrast = greycoprops(glcm, 'contrast').ravel()
    dissimilarity = greycoprops(glcm, 'dissimilarity').ravel()
    homogeneity = greycoprops(glcm, 'homogeneity').ravel()
    energy = greycoprops(glcm, 'energy').ravel()
    correlation = greycoprops(glcm, 'correlation').ravel()
    return np.hstack([contrast, dissimilarity, homogeneity, energy, correlation])

def load_data(folder_path):
    X = []
    y = []
    for label, class_name in enumerate(['benign', 'malignant']):
        class_folder = os.path.join(folder_path, class_name)
        for filename in os.listdir(class_folder):
            img_path = os.path.join(class_folder, filename)
            image = cv2.imread(img_path)
            features = extract_glcm_features(image)
            X.append(features)
            y.append(label)
    return np.array(X), np.array(y)


In [71]:
# Step 2: Load and preprocess training data
train_folder = "/content/extracted_data/archive (4)/train"
X_train, y_train = load_data(train_folder)

/usr/local/lib/python3.10/dist-packages/skimage/feature/__init__.py:35: skimage_deprecation: Function ``greycomatrix`` is deprecated and will be removed in version 1.0. Use ``skimage.feature.graycomatrix`` instead.
  removed_version='1.0')
/usr/local/lib/python3.10/dist-packages/skimage/feature/__init__.py:42: skimage_deprecation: Function ``greycoprops`` is deprecated and will be removed in version 1.0. Use ``skimage.feature.graycoprops`` instead.
  removed_version='1.0')
/usr/local/lib/python3.10/dist-packages/skimage/feature/__init__.py:42: skimage_deprecation: Function ``greycoprops`` is deprecated and will be removed in version 1.0. Use ``skimage.feature.graycoprops`` instead.
  removed_version='1.0')
/usr/local/lib/python3.10/dist-packages/skimage/feature/__init__.py:42: skimage_deprecation: Function ``greycoprops`` is deprecated and will be removed in version 1.0. Use ``skimage.feature.graycoprops`` instead.
  removed_version='1.0')
/usr/local/lib/python3.10/dist-packages/skimag

In [72]:
# Step 3: Load and preprocess testing data
test_folder = "/content/extracted_data/archive (4)/test"
X_test, y_test = load_data(test_folder)

/usr/local/lib/python3.10/dist-packages/skimage/feature/__init__.py:35: skimage_deprecation: Function ``greycomatrix`` is deprecated and will be removed in version 1.0. Use ``skimage.feature.graycomatrix`` instead.
  removed_version='1.0')
/usr/local/lib/python3.10/dist-packages/skimage/feature/__init__.py:42: skimage_deprecation: Function ``greycoprops`` is deprecated and will be removed in version 1.0. Use ``skimage.feature.graycoprops`` instead.
  removed_version='1.0')
/usr/local/lib/python3.10/dist-packages/skimage/feature/__init__.py:42: skimage_deprecation: Function ``greycoprops`` is deprecated and will be removed in version 1.0. Use ``skimage.feature.graycoprops`` instead.
  removed_version='1.0')
/usr/local/lib/python3.10/dist-packages/skimage/feature/__init__.py:42: skimage_deprecation: Function ``greycoprops`` is deprecated and will be removed in version 1.0. Use ``skimage.feature.graycoprops`` instead.
  removed_version='1.0')
/usr/local/lib/python3.10/dist-packages/skimag

In [73]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [74]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [75]:
# Step 4: Train Logistic Regression model
lr = LogisticRegression()
lr.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [76]:
# Step 5: Evaluate model
y_pred_lr = lr.predict(X_test)
accuracy = accuracy_score(y_test, y_pred_lr)
print("Accuracy:", accuracy)

Accuracy: 0.6705882352941176


In [77]:
from sklearn.metrics import accuracy_score, classification_report

In [78]:
accuracy_score(y_pred_lr,y_test)
print(classification_report(y_pred_lr,y_test))

              precision    recall  f1-score   support

           0       0.64      0.70      0.67        81
           1       0.70      0.64      0.67        89

    accuracy                           0.67       170
   macro avg       0.67      0.67      0.67       170
weighted avg       0.67      0.67      0.67       170



In [79]:
from sklearn.metrics import confusion_matrix

In [80]:
confusion_matrix(y_pred_lr,y_test)

array([[57, 24],
       [32, 57]])

Implementing a Random Forest Classifier

In [81]:
from sklearn.ensemble import RandomForestClassifier

In [82]:
rfc=RandomForestClassifier()

In [83]:
rfc.fit(X_train, y_train)

RandomForestClassifier()

In [84]:
y_pred_rfc = rfc.predict(X_test)
accuracy = accuracy_score(y_test, y_pred_rfc)
print("Accuracy:", accuracy)

Accuracy: 0.8117647058823529


In [85]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
import numpy as np

In [86]:
accuracy_score(y_pred_rfc,y_test)
print(classification_report(y_pred_rfc,y_test))

              precision    recall  f1-score   support

           0       0.79      0.84      0.81        83
           1       0.84      0.78      0.81        87

    accuracy                           0.81       170
   macro avg       0.81      0.81      0.81       170
weighted avg       0.81      0.81      0.81       170



In [88]:
confusion_matrix(y_pred_rfc,y_test)

array([[70, 13],
       [19, 68]])

Implementing a KNN

In [89]:
from sklearn.neighbors import KNeighborsClassifier

In [90]:
knn=KNeighborsClassifier(n_neighbors=7)

In [91]:
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=7)

In [92]:
y_pred_knn = knn.predict(X_test)
accuracy = accuracy_score(y_test, y_pred_knn)
print("Accuracy:", accuracy)

Accuracy: 0.7176470588235294


In [93]:
accuracy_score(y_pred_knn,y_test)
print(classification_report(y_pred_knn,y_test))

              precision    recall  f1-score   support

           0       0.61      0.81      0.69        67
           1       0.84      0.66      0.74       103

    accuracy                           0.72       170
   macro avg       0.72      0.73      0.72       170
weighted avg       0.75      0.72      0.72       170



In [94]:
confusion_matrix(y_pred_knn,y_test)

array([[54, 13],
       [35, 68]])

Implementing a Decision Tree

In [95]:
from sklearn.tree import DecisionTreeClassifier

In [96]:
dtc=DecisionTreeClassifier()

In [97]:
dtc.fit(X_train, y_train)

DecisionTreeClassifier()

In [98]:
y_pred_dtc = dtc.predict(X_test)
accuracy = accuracy_score(y_test, y_pred_dtc)
print("Accuracy:", accuracy)

Accuracy: 0.788235294117647


In [100]:
accuracy_score(y_pred_dtc,y_test)
print(classification_report(y_pred_dtc,y_test))

              precision    recall  f1-score   support

           0       0.76      0.82      0.79        83
           1       0.81      0.76      0.79        87

    accuracy                           0.79       170
   macro avg       0.79      0.79      0.79       170
weighted avg       0.79      0.79      0.79       170



In [101]:
confusion_matrix(y_pred_dtc,y_test)

array([[68, 15],
       [21, 66]])

Implementing a Naive Bayes classifier

In [102]:
from sklearn.naive_bayes import GaussianNB

In [103]:
nb=GaussianNB()

In [104]:
nb.fit(X_train, y_train)

GaussianNB()

In [105]:
y_pred_nb = nb.predict(X_test)
accuracy = accuracy_score(y_test, y_pred_nb)
print("Accuracy:", accuracy)

Accuracy: 0.6235294117647059


In [106]:
accuracy_score(y_pred_nb,y_test)
print(classification_report(y_pred_nb,y_test))

              precision    recall  f1-score   support

           0       0.66      0.63      0.65        93
           1       0.58      0.61      0.59        77

    accuracy                           0.62       170
   macro avg       0.62      0.62      0.62       170
weighted avg       0.63      0.62      0.62       170



In [107]:
confusion_matrix(y_pred_nb,y_test)

array([[59, 34],
       [30, 47]])

Xgboost

In [108]:
import xgboost as xgb

In [109]:
# Define the XGBoost classifier
xgb_model = xgb.XGBClassifier(objective='binary:logistic', random_state=42)

In [110]:
# Train the classifier
xgb_model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=42, ...)

In [111]:
# Make predictions on the test set
y_pred_xgb = xgb_model.predict(X_test)

In [112]:
# Evaluate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred_xgb)
print("Accuracy:", accuracy)

Accuracy: 0.8117647058823529


In [113]:
accuracy_score(y_pred_xgb,y_test)
print(classification_report(y_pred_xgb,y_test))

              precision    recall  f1-score   support

           0       0.78      0.85      0.81        81
           1       0.85      0.78      0.81        89

    accuracy                           0.81       170
   macro avg       0.81      0.81      0.81       170
weighted avg       0.82      0.81      0.81       170

