<a href="https://colab.research.google.com/github/PrajaktaPatil1/benign_malignant/blob/master/benign_malignant(with_ORB_feature).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import os
import numpy as np
import cv2
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [3]:
from google.colab import files
uploaded = files.upload()

Saving archive (update1).zip to archive (update1).zip


In [4]:
import os
import zipfile

# Path to the zip file
zip_file_path = '/content/archive (update1).zip'

# Directory where you want to extract the files
extracted_dir = '/content/extracted_data1'

# Ensure the directory exists
os.makedirs(extracted_dir, exist_ok=True)

# Extract the contents of the zip file
with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall(extracted_dir)

# List the contents of the extracted directory
extracted_files = os.listdir(extracted_dir)
print("Contents of the extracted directory:")
for file_name in extracted_files:
    print(file_name)

# Destination directory to save the extracted files
save_dir = '/content/saved_files'

Contents of the extracted directory:
archive (4)


In [5]:
# Step 1: Data Preprocessing

def extract_orb_features(image):
    orb = cv2.ORB_create()
    keypoints, descriptors = orb.detectAndCompute(image, None)
    return descriptors.flatten() if descriptors is not None else np.array([])

def load_data(folder_path):
    X = []
    y = []
    for label, class_name in enumerate(['benign', 'malignant']):
        class_folder = os.path.join(folder_path, class_name)
        for filename in os.listdir(class_folder):
            img_path = os.path.join(class_folder, filename)
            image = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
            features = extract_orb_features(image)
            X.append(features)
            y.append(label)
    return np.array(X), np.array(y)

In [6]:
def load_data(folder_path):
    X = []
    y = []
    max_descriptor_length = 0
    for label, class_name in enumerate(['benign', 'malignant']):
        class_folder = os.path.join(folder_path, class_name)
        for filename in os.listdir(class_folder):
            img_path = os.path.join(class_folder, filename)
            image = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
            features = extract_orb_features(image)
            if len(features) > max_descriptor_length:
                max_descriptor_length = len(features)
            X.append(features)
            y.append(label)

    # Pad features with zeros to ensure uniform length
    for i in range(len(X)):
        padded_features = np.zeros((max_descriptor_length,))
        padded_features[:len(X[i])] = X[i]
        X[i] = padded_features

    return np.array(X), np.array(y)


The End

In [7]:
train_folder = "/content/extracted_data1/archive (4)/train"
test_folder = "/content/extracted_data1/archive (4)/test"

In [8]:
X_train, y_train = load_data(os.path.join(train_folder))
X_test, y_test = load_data(os.path.join(test_folder))

In [9]:
# Step 1: Data Preprocessing

def extract_orb_features(image):
    orb = cv2.ORB_create()
    keypoints, descriptors = orb.detectAndCompute(image, None)
    return descriptors.flatten() if descriptors is not None else np.array([])

def load_data(folder_path):
    X = []
    y = []
    max_descriptor_length = 0
    for label, class_name in enumerate(['benign', 'malignant']):
        class_folder = os.path.join(folder_path, class_name)
        for filename in os.listdir(class_folder):
            img_path = os.path.join(class_folder, filename)
            image = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
            features = extract_orb_features(image)
            if len(features) > max_descriptor_length:
                max_descriptor_length = len(features)
            X.append(features)
            y.append(label)

    # Pad features with zeros to ensure uniform length
    for i in range(len(X)):
        padded_features = np.zeros((max_descriptor_length,))
        padded_features[:len(X[i])] = X[i]
        X[i] = padded_features

    return np.array(X), np.array(y)

In [10]:
# Step 2: Load and preprocess training data
train_folder = "/content/extracted_data1/archive (4)/train"
X_train, y_train = load_data(train_folder)

In [11]:
# Step 3: Load and preprocess testing data
test_folder = "/content/extracted_data1/archive (4)/test"
X_test, y_test = load_data(test_folder)

Model Training

In [12]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [14]:
# Step 1: Train Logistic Regression classifier
lr = LogisticRegression()
lr.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [15]:
from sklearn.model_selection import GridSearchCV

In [16]:
# Define hyperparameters grid
param_grid = {
    'penalty': ['l1', 'l2'],
    'C': [0.001, 0.01, 0.1, 1, 10, 100]
}

In [17]:
# Initialize GridSearchCV
grid_search = GridSearchCV(estimator=LogisticRegression(), param_grid=param_grid, cv=5)

In [18]:
# Fit the grid search to the data
grid_search.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [0.001, 0.01, 0.1, 1, 10, 100],
                         'penalty': ['l1', 'l2']})

In [19]:
# Get the best hyperparameters
best_params = grid_search.best_params_
print("Best hyperparameters:", best_params)

Best hyperparameters: {'C': 0.01, 'penalty': 'l2'}


In [20]:
# Initialize Logistic Regression with best hyperparameters
lr_tuned = LogisticRegression(**best_params)

In [21]:
# Fit the model with tuned hyperparameters
lr_tuned.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(C=0.01)

In [22]:
y_pred_lr = lr_tuned.predict(X_test)
accuracy = accuracy_score(y_test, y_pred_lr)
print("Accuracy:", accuracy)

Accuracy: 0.8675496688741722


In [23]:
from sklearn.metrics import accuracy_score, classification_report

In [25]:
accuracy_score(y_pred_lr,y_test)
print(classification_report(y_pred_lr,y_test))

              precision    recall  f1-score   support

           0       0.83      0.88      0.85        66
           1       0.90      0.86      0.88        85

    accuracy                           0.87       151
   macro avg       0.86      0.87      0.87       151
weighted avg       0.87      0.87      0.87       151



In [26]:
from sklearn.metrics import confusion_matrix

In [27]:
confusion_matrix(y_pred_lr,y_test)

array([[58,  8],
       [12, 73]])

In [31]:
y_pred_lr = lr_tuned.predict(X_test)
accuracy = accuracy_score(y_test, y_pred_lr)
print("Accuracy:", accuracy)

Accuracy: 0.8675496688741722


In [29]:
y_pred_lr2 = lr_tuned.predict(X_test)
accuracy = accuracy_score(y_test, y_pred_lr)
print("Accuracy:", accuracy)

Accuracy: 0.8675496688741722


Implementing a Random Forest Classifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rfc=RandomForestClassifier()

In [ ]:
rfc.fit(X_train, y_train)

RandomForestClassifier()

In [ ]:
y_pred_rfc = rfc.predict(X_test)
accuracy = accuracy_score(y_test, y_pred_rfc)
print("Accuracy:", accuracy)

Accuracy: 0.8543046357615894


In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
import numpy as np

In [ ]:
accuracy_score(y_pred_rfc,y_test)
print(classification_report(y_pred_rfc,y_test))

              precision    recall  f1-score   support

           0       0.77      0.90      0.83        60
           1       0.93      0.82      0.87        91

    accuracy                           0.85       151
   macro avg       0.85      0.86      0.85       151
weighted avg       0.86      0.85      0.86       151



In [ ]:
confusion_matrix(y_pred_rfc,y_test)

array([[54,  6],
       [16, 75]])

Implementing a KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
knn=KNeighborsClassifier(n_neighbors=7)

In [ ]:
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=7)

In [ ]:
y_pred_knn = knn.predict(X_test)
accuracy = accuracy_score(y_test, y_pred_knn)
print("Accuracy:", accuracy)

Accuracy: 0.7748344370860927


In [ ]:
accuracy_score(y_pred_knn,y_test)
print(classification_report(y_pred_knn,y_test))

              precision    recall  f1-score   support

           0       0.67      0.81      0.73        58
           1       0.86      0.75      0.80        93

    accuracy                           0.77       151
   macro avg       0.77      0.78      0.77       151
weighted avg       0.79      0.77      0.78       151



In [ ]:
confusion_matrix(y_pred_knn,y_test)

array([[47, 11],
       [23, 70]])

Implementing a Decision Tree

In [53]:
from sklearn.tree import DecisionTreeClassifier

In [54]:
dtc=DecisionTreeClassifier()

In [55]:
dtc.fit(X_train, y_train)

DecisionTreeClassifier()

In [56]:
y_pred_dtc = dtc.predict(X_test)
accuracy = accuracy_score(y_test, y_pred_dtc)
print("Accuracy:", accuracy)

Accuracy: 0.7880794701986755


In [57]:
accuracy_score(y_pred_dtc,y_test)
print(classification_report(y_pred_dtc,y_test))

              precision    recall  f1-score   support

           0       0.77      0.77      0.77        70
           1       0.80      0.80      0.80        81

    accuracy                           0.79       151
   macro avg       0.79      0.79      0.79       151
weighted avg       0.79      0.79      0.79       151



In [58]:
confusion_matrix(y_pred_dtc,y_test)

array([[54, 16],
       [16, 65]])

Implementing a Naive Bayes classifier

In [59]:
from sklearn.naive_bayes import GaussianNB

In [60]:
nb=GaussianNB()

In [61]:
nb.fit(X_train, y_train)

GaussianNB()

In [62]:
y_pred_nb = nb.predict(X_test)
accuracy = accuracy_score(y_test, y_pred_nb)
print("Accuracy:", accuracy)

Accuracy: 0.5298013245033113


In [63]:
accuracy_score(y_pred_nb,y_test)
print(classification_report(y_pred_nb,y_test))

              precision    recall  f1-score   support

           0       0.89      0.50      0.64       125
           1       0.22      0.69      0.34        26

    accuracy                           0.53       151
   macro avg       0.55      0.59      0.49       151
weighted avg       0.77      0.53      0.58       151



In [64]:
confusion_matrix(y_pred_nb,y_test)

array([[62, 63],
       [ 8, 18]])

Xgboost

In [65]:
import xgboost as xgb

In [66]:
# Define the XGBoost classifier
xgb_model = xgb.XGBClassifier(objective='binary:logistic', random_state=42)

In [67]:
# Train the classifier
xgb_model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=42, ...)

In [68]:
# Make predictions on the test set
y_pred_xgb = xgb_model.predict(X_test)

In [69]:
# Evaluate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred_xgb)
print("Accuracy:", accuracy)

Accuracy: 0.847682119205298


In [70]:
from sklearn.metrics import accuracy_score, classification_report

In [71]:
accuracy_score(y_pred_xgb,y_test)
print(classification_report(y_pred_xgb,y_test))

              precision    recall  f1-score   support

           0       0.76      0.90      0.82        59
           1       0.93      0.82      0.87        92

    accuracy                           0.85       151
   macro avg       0.84      0.86      0.84       151
weighted avg       0.86      0.85      0.85       151



In [72]:
from sklearn.metrics import confusion_matrix

In [73]:
confusion_matrix(y_pred_xgb,y_test)

array([[53,  6],
       [17, 75]])

SVM

In [77]:
from sklearn.svm import SVC
from sklearn.pipeline import Pipeline
from sklearn.decomposition import PCA

In [78]:
svm_model = Pipeline([
    ("PCA", PCA(n_components=100)),  # Optional: PCA for dimensionality reduction
    ("SVM", SVC(kernel="rbf", C=10))
])

In [80]:
svm_model.fit(X_train, y_train)

Pipeline(steps=[('PCA', PCA(n_components=100)), ('SVM', SVC(C=10))])

In [86]:
# Step 4: Model Evaluation
y_pred_svm = svm_model.predict(X_test)
test_accuracy = accuracy_score(y_test, y_pred_svm)
print("Test Accuracy:", test_accuracy)

Test Accuracy: 0.7947019867549668


In [87]:
# Step 5: Model Evaluation Metrics
print(classification_report(y_pred_svm, y_test))

              precision    recall  f1-score   support

           0       0.70      0.83      0.76        59
           1       0.88      0.77      0.82        92

    accuracy                           0.79       151
   macro avg       0.79      0.80      0.79       151
weighted avg       0.81      0.79      0.80       151



In [88]:
confusion_matrix(y_pred_svm,y_test)

array([[49, 10],
       [21, 71]])

MLP

In [90]:
from sklearn.neural_network import MLPClassifier

In [91]:
# Initialize the MLPClassifier
mlp = MLPClassifier(hidden_layer_sizes=(100,), activation='relu', solver='adam', max_iter=1000, random_state=42)

In [93]:
# Train the model
mlp.fit(X_train, y_train)

MLPClassifier(max_iter=1000, random_state=42)

In [95]:
# Predict on the test set
y_pred = mlp.predict(X_test)

In [96]:
# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.7417218543046358
