<a href="https://colab.research.google.com/github/PrajaktaPatil1/benign_malignant/blob/master/benign_malignant(with_ORB_feature).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import os
import numpy as np
import cv2
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [2]:
from google.colab import files
uploaded = files.upload()

Saving archive (update1).zip to archive (update1).zip


In [11]:
import os
import zipfile

# Path to the zip file
zip_file_path = '/content/archive (update1).zip'

# Directory where you want to extract the files
extracted_dir = '/content/extracted_data1'

# Ensure the directory exists
os.makedirs(extracted_dir, exist_ok=True)

# Extract the contents of the zip file
with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall(extracted_dir)

# List the contents of the extracted directory
extracted_files = os.listdir(extracted_dir)
print("Contents of the extracted directory:")
for file_name in extracted_files:
    print(file_name)

# Destination directory to save the extracted files
save_dir = '/content/saved_files'

Contents of the extracted directory:
archive (4)


In [4]:
# Step 1: Data Preprocessing

def extract_orb_features(image):
    orb = cv2.ORB_create()
    keypoints, descriptors = orb.detectAndCompute(image, None)
    return descriptors.flatten() if descriptors is not None else np.array([])

def load_data(folder_path):
    X = []
    y = []
    for label, class_name in enumerate(['benign', 'malignant']):
        class_folder = os.path.join(folder_path, class_name)
        for filename in os.listdir(class_folder):
            img_path = os.path.join(class_folder, filename)
            image = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
            features = extract_orb_features(image)
            X.append(features)
            y.append(label)
    return np.array(X), np.array(y)

In [5]:
def load_data(folder_path):
    X = []
    y = []
    max_descriptor_length = 0
    for label, class_name in enumerate(['benign', 'malignant']):
        class_folder = os.path.join(folder_path, class_name)
        for filename in os.listdir(class_folder):
            img_path = os.path.join(class_folder, filename)
            image = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
            features = extract_orb_features(image)
            if len(features) > max_descriptor_length:
                max_descriptor_length = len(features)
            X.append(features)
            y.append(label)

    # Pad features with zeros to ensure uniform length
    for i in range(len(X)):
        padded_features = np.zeros((max_descriptor_length,))
        padded_features[:len(X[i])] = X[i]
        X[i] = padded_features

    return np.array(X), np.array(y)


In [12]:
train_folder = "/content/extracted_data1/archive (4)/train"
test_folder = "/content/extracted_data1/archive (4)/test"

In [13]:
X_train, y_train = load_data(os.path.join(train_folder))
X_test, y_test = load_data(os.path.join(test_folder))

In [14]:
# Step 1: Data Preprocessing

def extract_orb_features(image):
    orb = cv2.ORB_create()
    keypoints, descriptors = orb.detectAndCompute(image, None)
    return descriptors.flatten() if descriptors is not None else np.array([])

def load_data(folder_path):
    X = []
    y = []
    max_descriptor_length = 0
    for label, class_name in enumerate(['benign', 'malignant']):
        class_folder = os.path.join(folder_path, class_name)
        for filename in os.listdir(class_folder):
            img_path = os.path.join(class_folder, filename)
            image = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
            features = extract_orb_features(image)
            if len(features) > max_descriptor_length:
                max_descriptor_length = len(features)
            X.append(features)
            y.append(label)

    # Pad features with zeros to ensure uniform length
    for i in range(len(X)):
        padded_features = np.zeros((max_descriptor_length,))
        padded_features[:len(X[i])] = X[i]
        X[i] = padded_features

    return np.array(X), np.array(y)

In [15]:
# Step 2: Load and preprocess training data
train_folder = "/content/extracted_data1/archive (4)/train"
X_train, y_train = load_data(train_folder)

In [16]:
# Step 3: Load and preprocess testing data
test_folder = "/content/extracted_data1/archive (4)/test"
X_test, y_test = load_data(test_folder)

Model Training

In [17]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [18]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [19]:
# Step 1: Train Logistic Regression classifier
lr = LogisticRegression()
lr.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [20]:
# Step 5: Evaluate model
y_pred_lr = lr.predict(X_test)
accuracy = accuracy_score(y_test, y_pred_lr)
print("Accuracy:", accuracy)

Accuracy: 0.847682119205298


In [21]:
from sklearn.metrics import accuracy_score, classification_report

In [22]:
accuracy_score(y_pred_lr,y_test)
print(classification_report(y_pred_lr,y_test))

              precision    recall  f1-score   support

           0       0.84      0.83      0.84        71
           1       0.85      0.86      0.86        80

    accuracy                           0.85       151
   macro avg       0.85      0.85      0.85       151
weighted avg       0.85      0.85      0.85       151



In [23]:
from sklearn.metrics import confusion_matrix

In [24]:
confusion_matrix(y_pred_lr,y_test)

array([[59, 12],
       [11, 69]])

Implementing a Random Forest Classifier

In [25]:
from sklearn.ensemble import RandomForestClassifier

In [26]:
rfc=RandomForestClassifier()

In [27]:
rfc.fit(X_train, y_train)

RandomForestClassifier()

In [28]:
y_pred_rfc = rfc.predict(X_test)
accuracy = accuracy_score(y_test, y_pred_rfc)
print("Accuracy:", accuracy)

Accuracy: 0.8543046357615894


In [29]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
import numpy as np

In [30]:
accuracy_score(y_pred_rfc,y_test)
print(classification_report(y_pred_rfc,y_test))

              precision    recall  f1-score   support

           0       0.77      0.90      0.83        60
           1       0.93      0.82      0.87        91

    accuracy                           0.85       151
   macro avg       0.85      0.86      0.85       151
weighted avg       0.86      0.85      0.86       151



In [31]:
confusion_matrix(y_pred_rfc,y_test)

array([[54,  6],
       [16, 75]])

Implementing a KNN

In [32]:
from sklearn.neighbors import KNeighborsClassifier

In [33]:
knn=KNeighborsClassifier(n_neighbors=7)

In [34]:
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=7)

In [35]:
y_pred_knn = knn.predict(X_test)
accuracy = accuracy_score(y_test, y_pred_knn)
print("Accuracy:", accuracy)

Accuracy: 0.7748344370860927


In [36]:
accuracy_score(y_pred_knn,y_test)
print(classification_report(y_pred_knn,y_test))

              precision    recall  f1-score   support

           0       0.67      0.81      0.73        58
           1       0.86      0.75      0.80        93

    accuracy                           0.77       151
   macro avg       0.77      0.78      0.77       151
weighted avg       0.79      0.77      0.78       151



In [37]:
confusion_matrix(y_pred_knn,y_test)

array([[47, 11],
       [23, 70]])

Implementing a Decision Tree

In [38]:
from sklearn.tree import DecisionTreeClassifier

In [39]:
dtc=DecisionTreeClassifier()

In [40]:
dtc.fit(X_train, y_train)

DecisionTreeClassifier()

In [41]:
y_pred_dtc = dtc.predict(X_test)
accuracy = accuracy_score(y_test, y_pred_dtc)
print("Accuracy:", accuracy)

Accuracy: 0.7947019867549668


In [42]:
accuracy_score(y_pred_dtc,y_test)
print(classification_report(y_pred_dtc,y_test))

              precision    recall  f1-score   support

           0       0.77      0.78      0.78        69
           1       0.81      0.80      0.81        82

    accuracy                           0.79       151
   macro avg       0.79      0.79      0.79       151
weighted avg       0.79      0.79      0.79       151



In [43]:
confusion_matrix(y_pred_dtc,y_test)

array([[54, 15],
       [16, 66]])

Implementing a Naive Bayes classifier

In [44]:
from sklearn.naive_bayes import GaussianNB

In [45]:
nb=GaussianNB()

In [46]:
nb.fit(X_train, y_train)

GaussianNB()

In [47]:
y_pred_nb = nb.predict(X_test)
accuracy = accuracy_score(y_test, y_pred_nb)
print("Accuracy:", accuracy)

Accuracy: 0.5298013245033113


In [48]:
accuracy_score(y_pred_nb,y_test)
print(classification_report(y_pred_nb,y_test))

              precision    recall  f1-score   support

           0       0.89      0.50      0.64       125
           1       0.22      0.69      0.34        26

    accuracy                           0.53       151
   macro avg       0.55      0.59      0.49       151
weighted avg       0.77      0.53      0.58       151



In [49]:
confusion_matrix(y_pred_nb,y_test)

array([[62, 63],
       [ 8, 18]])

Xgboost

In [50]:
import xgboost as xgb

In [51]:
# Define the XGBoost classifier
xgb_model = xgb.XGBClassifier(objective='binary:logistic', random_state=42)

In [52]:
# Train the classifier
xgb_model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=42, ...)

In [53]:
# Make predictions on the test set
y_pred_xgb = xgb_model.predict(X_test)

In [54]:
# Evaluate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred_xgb)
print("Accuracy:", accuracy)

Accuracy: 0.847682119205298


In [55]:
accuracy_score(y_pred_xgb,y_test)
print(classification_report(y_pred_xgb,y_test))

              precision    recall  f1-score   support

           0       0.76      0.90      0.82        59
           1       0.93      0.82      0.87        92

    accuracy                           0.85       151
   macro avg       0.84      0.86      0.84       151
weighted avg       0.86      0.85      0.85       151

